### ISSUE TITLE
GSD-2022-1000006: array in "product_name"

### ISSUE THREAD

**Issue by evdenis** [cloudsecurityalliance/gsd-database#2146]
Are you sure about using array in "product_name" field?

https://github.com/cloudsecurityalliance/gsd-database/blob/d20eabbf6ba66de1ae86d379cb4ad35139bc3821/2022/1000xxx/GSD-2022-1000006.json#L5-L7

**Comment by kurtseifried** [comment]
So this is in the GSD namespace which doesn't have an official data schema yet (and hopefully never does), we currently use OSV primarily, but also the CVE JSON format (which I invented and has terrible problems), one problem both OSV and CVE JSON have is:

Some strings are singular, e.g. a timestamp, ID.

But many strings should allow multiple values, e.g. what is the name of the package? log4j? log4j2? log4j v2?

So my current thinking is all strings, unless proven to be singular (e.g. timestamps/IDs), should be arrays that can safely/sanely hold multiple values. E.g. the GHSA advisory calls it "H2 Console".

**Comment by evdenis** [comment]
thanks

**Comment by kurtseifried** [comment]
Also to be clear I'm open to alternative suggestions. e.g. I had the thought "what if we allow things to be a string or an array if there are multiple", but then every code has to check "is this a string or an array" and I went with "just make them all arrays" in my head which I think makes sense, but I have been known to be wrong.

**Comment by evdenis** [comment]
Does it mean that you will change product_name to array in all existing files?
Fields like id, data_type, data_version, ... probably can't be arrays.

**Comment by kurtseifried** [comment]
Not decided yet. Part of this is generating data, then looking at what we need. I think a common case would be product name being different, but for example, metadata (timestamp, data_version, etc.) is generally one value only. Usually, part of this is an exploration and not trying to pre-optimize everything (like I did with the CVE JSON format which is a train wreck in the real world).
