### ISSUE TITLE
wanted to add dark mode button

### ISSUE THREAD

**Issue by Parth4git** [cloudsecurityalliance/gsd-database#2494]
@cloudsecurityalliance do you want to add a dark mode button

**Comment by oswalpalash** [comment]
@Parth4git this might be more of a gsd-tools (https://github.com/cloudsecurityalliance/gsd-tools/issues) issue than a gsd-database item.

**Comment by Parth4git** [comment]
In https://gsd.id/getting-started there need of dark  mode
feature button
Kindly assign this issue to me

**Comment by oswalpalash** [comment]
I'm going to close it out as not really an *issue* on the gsd-database project. Feel free to open an item to track it on the gsd-tools repo. This repo is just a database.
